substrate.cassandra.journal.prefix=substrate:journal:
substrate.cassandra.journal.table-name=substrate_journal
substrate.cassandra.journal.auto-create-schema=true
substrate.cassandra.journal.default-ttl=24h
substrate.cassandra.atom.prefix=substrate:atom:
substrate.cassandra.atom.table-name=substrate_atoms
substrate.cassandra.atom.auto-create-schema=true
