substrate.cassandra.journal.prefix=substrate:journal:
substrate.cassandra.journal.table-name=substrate_journal
substrate.cassandra.journal.auto-create-schema=true
substrate.cassandra.journal.default-ttl=24h
