substrate.redis.atom.prefix=substrate:atom:
substrate.redis.journal.prefix=substrate:journal:
substrate.redis.journal.max-len=100000
substrate.redis.journal.default-ttl=1h
substrate.redis.mailbox.prefix=substrate:mailbox:
substrate.redis.notifier.channel-prefix=substrate:notify:
