substrate.postgresql.journal.prefix=substrate:journal:
substrate.postgresql.journal.max-len=100000
substrate.postgresql.journal.auto-create-schema=true
substrate.postgresql.mailbox.prefix=substrate:mailbox:
substrate.postgresql.mailbox.auto-create-schema=true
substrate.postgresql.notifier.channel=substrate_notify
substrate.postgresql.notifier.poll-timeout=500ms
