substrate.rabbitmq.journal.prefix=substrate:journal:
substrate.rabbitmq.journal.max-age=24h
substrate.rabbitmq.journal.max-length-bytes=1073741824
substrate.rabbitmq.notifier.exchange-name=substrate-notify
