substrate.mongodb.journal.enabled=true
substrate.mongodb.journal.prefix=substrate:journal:
substrate.mongodb.journal.collection-name=substrate_journal
substrate.mongodb.journal.ttl=24h
substrate.mongodb.mailbox.enabled=true
substrate.mongodb.mailbox.prefix=substrate:mailbox:
substrate.mongodb.mailbox.collection-name=substrate_mailbox
substrate.mongodb.mailbox.default-ttl=5m
