substrate.atom.max-ttl=24h
substrate.journal.max-inactivity-ttl=24h
substrate.journal.max-entry-ttl=7d
substrate.journal.max-retention-ttl=30d
substrate.journal.subscription.queue-capacity=1024
substrate.mailbox.max-ttl=30m
