substrate.hazelcast.atom.enabled=true
substrate.hazelcast.atom.prefix=substrate:atom:
substrate.hazelcast.atom.map-name=substrate-atoms
substrate.hazelcast.journal.enabled=true
substrate.hazelcast.journal.prefix=substrate:journal:
substrate.hazelcast.journal.ringbuffer-capacity=100000
substrate.hazelcast.journal.ringbuffer-ttl=1h
substrate.hazelcast.mailbox.enabled=true
substrate.hazelcast.mailbox.prefix=substrate:mailbox:
substrate.hazelcast.mailbox.map-name=substrate-mailbox
substrate.hazelcast.mailbox.default-ttl=5m
substrate.hazelcast.notifier.enabled=true
substrate.hazelcast.notifier.topic-name=substrate-notify
