substrate.dynamodb.journal.prefix=substrate:journal:
substrate.dynamodb.journal.table-name=substrate_journal
substrate.dynamodb.journal.auto-create-table=true
substrate.dynamodb.journal.ttl=24h
substrate.dynamodb.mailbox.prefix=substrate:mailbox:
substrate.dynamodb.mailbox.table-name=substrate_mailbox
substrate.dynamodb.mailbox.auto-create-table=true
substrate.dynamodb.mailbox.default-ttl=5m
substrate.dynamodb.atom.prefix=substrate:atom:
substrate.dynamodb.atom.table-name=substrate_atoms
substrate.dynamodb.atom.auto-create-table=true
