substrate.journal.cassandra.prefix=substrate:journal:
substrate.journal.cassandra.table-name=substrate_journal
substrate.journal.cassandra.auto-create-schema=true
substrate.journal.cassandra.default-ttl=24h
