substrate.mailbox.dynamodb.prefix=substrate:mailbox:
substrate.mailbox.dynamodb.table-name=substrate_mailbox
substrate.mailbox.dynamodb.auto-create-table=true
substrate.mailbox.dynamodb.default-ttl=5m
